import { RouteTree } from '/@/types/route-tree'
const ROUTE_TREE: RouteTree[] = [
    {
        key:'/home',
        name:'首页'
    },
    {
        key:'/doc',
        name:'文档'
    },
    {
        key:'/permission',
        name:'权限测试'
    },
    {
        key:'/icon',
        name:'图标'
    },
    {
        key:'/component',
        name:'组件'
    },
    {
        key:'/chart',
        name:'图表'
    },
    {
        key:'/example',
        name:'综合实例'
    },
    {
        key:'/form',
        name:'表单'
    },
    {
        key:'/error',
        name:'错误页面'
    },
    {
        key:'/log',
        name:'错误日志'
    },
    {
        key:'/excel',
        name:'excel'
    }
];
export default ROUTE_TREE;